{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.strobfuscator",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 72002,
          "sha512": "ba3a4ed915b2dd750a212fd7f0454f126cba53c7c3e9fd8cbdb00a37a897dadb3e14555921b7904b00b7bddeac7d690023205e3b37efa58e4497d3d1e627ad4a",
          "sha256": "2a2c6acc2e6ca8251c799cd9a6770e63b09972fb5aaabb7c19e9f23712459391",
          "sha1": "962f0dc2c417b1709c7a5fd2408e1f1f75d43746",
          "md5": "0dd0e637c5c4d2a50a219b816402ae3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 72002,
          "sha512": "ba3a4ed915b2dd750a212fd7f0454f126cba53c7c3e9fd8cbdb00a37a897dadb3e14555921b7904b00b7bddeac7d690023205e3b37efa58e4497d3d1e627ad4a",
          "sha256": "2a2c6acc2e6ca8251c799cd9a6770e63b09972fb5aaabb7c19e9f23712459391",
          "sha1": "962f0dc2c417b1709c7a5fd2408e1f1f75d43746",
          "md5": "0dd0e637c5c4d2a50a219b816402ae3f"
        }
      ]
    }
  ]
}
