{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.obfuscator",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 49222,
          "sha512": "0278d8ed26b0e1cdebabdf667b4bc9e5fc928e31652be5ee0a7b269466d1ae6ffeb38c975611d044b942ad3fbbc6ea8d84b9078f041f496424733aa23d4079d3",
          "sha256": "09202bb0e8c2671860056f28358c136b0f823dc6faccb737693c17bfda44ea09",
          "sha1": "3614729d551705c5d192e7f9c3d950a0ea637051",
          "md5": "ddb971304af763617d2716c446366b3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 49222,
          "sha512": "0278d8ed26b0e1cdebabdf667b4bc9e5fc928e31652be5ee0a7b269466d1ae6ffeb38c975611d044b942ad3fbbc6ea8d84b9078f041f496424733aa23d4079d3",
          "sha256": "09202bb0e8c2671860056f28358c136b0f823dc6faccb737693c17bfda44ea09",
          "sha1": "3614729d551705c5d192e7f9c3d950a0ea637051",
          "md5": "ddb971304af763617d2716c446366b3d"
        }
      ]
    }
  ]
}
