{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.obfuscator",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 53662,
          "sha512": "99b69a4bab5cdbf1d48dfd69eac8d449efa3d56d12b84f030947021ac5b2facea0745a03bf6ff9d9bed25dc4576dc5a3de332e7bfe49ebcd4ca7ca02a1ae949b",
          "sha256": "6d5db3207b4cc7758009b6a995db8af0d0e15c5fd5af60c09d0b81811065736e",
          "sha1": "9d9846f140a7ba47463ce355a3c264e429953f67",
          "md5": "d142e9357c6de20af887964e53c68c37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 53662,
          "sha512": "99b69a4bab5cdbf1d48dfd69eac8d449efa3d56d12b84f030947021ac5b2facea0745a03bf6ff9d9bed25dc4576dc5a3de332e7bfe49ebcd4ca7ca02a1ae949b",
          "sha256": "6d5db3207b4cc7758009b6a995db8af0d0e15c5fd5af60c09d0b81811065736e",
          "sha1": "9d9846f140a7ba47463ce355a3c264e429953f67",
          "md5": "d142e9357c6de20af887964e53c68c37"
        }
      ]
    }
  ]
}
