{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.obfuscator",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 54050,
          "sha512": "df79d62d15c4ae92de52ca00a605ac5a55beb11c2a1e49875b5aa09a4b3b09afea21f12b2ce6d893838b343b331d1e8362adc39d493372bbbda47e9311b89e5c",
          "sha256": "1396e932e8c26249b6cb085f7e982eb698be92c21dfa53624b865d01f4cede0e",
          "sha1": "a14eef7850f4906aa2f5bc2b2481a3601fe2be6d",
          "md5": "504e79473b057f98200cb324d6e8a170"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 54050,
          "sha512": "df79d62d15c4ae92de52ca00a605ac5a55beb11c2a1e49875b5aa09a4b3b09afea21f12b2ce6d893838b343b331d1e8362adc39d493372bbbda47e9311b89e5c",
          "sha256": "1396e932e8c26249b6cb085f7e982eb698be92c21dfa53624b865d01f4cede0e",
          "sha1": "a14eef7850f4906aa2f5bc2b2481a3601fe2be6d",
          "md5": "504e79473b057f98200cb324d6e8a170"
        }
      ]
    }
  ]
}
