{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.obfuscator",
    "module": "xor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1484,
          "sha512": "a7244bbb3f0475f5e3729bd11799674bedf6be5f1be80d5af571b0a9c7a78a7fcbde5e2e0e200af158216e0656e9cf3f13d5167f520cb8aca9b97712aa751bee",
          "sha256": "328a230b9033f6a1fb27ab1bbb888130781b9be4f8b2db54e00652348d121f44",
          "sha1": "4f371938301fc5d9fc148024e555a565e3ff1a8e",
          "md5": "8cae2395b3cf9af3229d6bb863419438"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1484,
          "sha512": "a7244bbb3f0475f5e3729bd11799674bedf6be5f1be80d5af571b0a9c7a78a7fcbde5e2e0e200af158216e0656e9cf3f13d5167f520cb8aca9b97712aa751bee",
          "sha256": "328a230b9033f6a1fb27ab1bbb888130781b9be4f8b2db54e00652348d121f44",
          "sha1": "4f371938301fc5d9fc148024e555a565e3ff1a8e",
          "md5": "8cae2395b3cf9af3229d6bb863419438"
        }
      ]
    }
  ]
}
