{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.obfuscator",
    "module": "xor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1491,
          "sha512": "143f247289f8899259f396a3f640f1c1845899de787900ccef2ea11e800410ce6aea57a67633be0b65d8e69621456c26ce666fdf9ca25c5fefd8f6ff735c2100",
          "sha256": "efa87f9fc80e6fb25ff33a8bf4cc2f24fa7d957bc0fd62799b66086b675d72ff",
          "sha1": "2eb513a2fca77c3fbfcf8abe578f495c5b81e39e",
          "md5": "acafad5a86c0351e34ed097994aef8a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1491,
          "sha512": "143f247289f8899259f396a3f640f1c1845899de787900ccef2ea11e800410ce6aea57a67633be0b65d8e69621456c26ce666fdf9ca25c5fefd8f6ff735c2100",
          "sha256": "efa87f9fc80e6fb25ff33a8bf4cc2f24fa7d957bc0fd62799b66086b675d72ff",
          "sha1": "2eb513a2fca77c3fbfcf8abe578f495c5b81e39e",
          "md5": "acafad5a86c0351e34ed097994aef8a5"
        }
      ]
    }
  ]
}
