{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.obfuscator",
    "module": "xor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1491,
          "sha512": "141b221f82b512b15ffc064b734917177f2669ae4afc0098b456abe5e489060bc676a0146296f3b8811e00e34cd3444ad9bb09f92ed16ab2ba95f76b7f595254",
          "sha256": "2b3f5058141c128ed5d87cd997dad11053cd58db5bb8d2d2af7660c98e6c46ac",
          "sha1": "726bc46255933b0473994b6f5e33daf9471750d1",
          "md5": "7b9600fc55a74d9feefba75c2c51d79b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1491,
          "sha512": "141b221f82b512b15ffc064b734917177f2669ae4afc0098b456abe5e489060bc676a0146296f3b8811e00e34cd3444ad9bb09f92ed16ab2ba95f76b7f595254",
          "sha256": "2b3f5058141c128ed5d87cd997dad11053cd58db5bb8d2d2af7660c98e6c46ac",
          "sha1": "726bc46255933b0473994b6f5e33daf9471750d1",
          "md5": "7b9600fc55a74d9feefba75c2c51d79b"
        }
      ]
    }
  ]
}
