{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nullptrx.strobfuscator",
    "module": "xor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1391,
          "sha512": "838d1c43eb63a90a83ce89171cb2bc2a6cc48333ff77dd2c2cdfd0a55f932eb4c1a1da814df79b43474e427556018abadb7f3e3c7899a1609d5806d2edb376d0",
          "sha256": "36eec4e637c95fe96d2a669b82a102ab3dd14e5a4708a62fa19c6b0a159bd768",
          "sha1": "159991c0167cea85a16e9aa46d1c57a27859e97a",
          "md5": "9f3fcae3de50b2be8d87f0d3b22afaf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xor-1.0.0.jar",
          "url": "xor-1.0.0.jar",
          "size": 1391,
          "sha512": "838d1c43eb63a90a83ce89171cb2bc2a6cc48333ff77dd2c2cdfd0a55f932eb4c1a1da814df79b43474e427556018abadb7f3e3c7899a1609d5806d2edb376d0",
          "sha256": "36eec4e637c95fe96d2a669b82a102ab3dd14e5a4708a62fa19c6b0a159bd768",
          "sha1": "159991c0167cea85a16e9aa46d1c57a27859e97a",
          "md5": "9f3fcae3de50b2be8d87f0d3b22afaf5"
        }
      ]
    }
  ]
}
